// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnW6J8IIsVv6zGbNo30XCI5e3xWWcSBRg',
    appId: '1:832632944780:android:6a58c7053e2777b17163a9',
    messagingSenderId: '832632944780',
    projectId: 'paediatric-dental-app-6b4c3',
    storageBucket: 'paediatric-dental-app-6b4c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMD-Iwv8rC0AKwgTdLYzA_2-keIbLVHmQ',
    appId: '1:832632944780:ios:0d24cd9f0de5881f7163a9',
    messagingSenderId: '832632944780',
    projectId: 'paediatric-dental-app-6b4c3',
    storageBucket: 'paediatric-dental-app-6b4c3.firebasestorage.app',
    androidClientId: '832632944780-vecaknkl65tllvm41utgi5ka1pjot38a.apps.googleusercontent.com',
    iosClientId: '832632944780-o9cg7vr3sqf24je1su7lostchcvdfsjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttrApp',
  );

}